language: node_js
node_js:
- node
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-multilib
    - g++-multilib
os:
- osx
- linux
dist: xenial
before_deploy:
- ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
- npm install
- npm run prebuild
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ARCH=ia32 npm run prebuild; fi
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/prebuilds"
  .
deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: node
  api_key:
    secure: o1VZ74oj+vPJ/AYT7jYmiXDAFqRz58JsUrU2BDmLhat237uhohp/bpIBbxZupHjTDEmapRFPngcOVV23OZrR9+lYpJmwn2Nv1ezivKhBbSFFPUoAUJAzDhQD/+aVbp43YKsHzjhG5bg0tpiPrw/MGW3y9jVnhFmRGssLWUHO9z5PhErVLPjhdhqRs1/pripA+wiLqtGD43jJrn2MMSNTqqBKilwYvV0wI7Xo4FgCMJjpqvRxEj7PwAssyUiQqzWmceNiiKpS6HSXR9S7iG2Zjz/uMFIeVnCca69qLca/7dbjFOAtVJF9o2FspDsg5ipZ2wkJWomtf49vku/fWHL7b+mepgs8buxPqu14Yyawz6BLso2YFC5Zm6RZmLWYGl9xr3dRmQbd4o3kQhkSIQJonbm8GI2rrj8V6TNCBWNJdnqXvURTquJVtqqsyxR5zghGQDxO7p5SK79KIFIsHtYt2VTF/CaxaTR9xHs+/W6KSYNEXO/zYME9wy51gX5p0iY+V8BCMm6eaWcC8uiPppCRb4PoLzp7vaJDGawKLvWWfEaW1xhC0CmMCyk2dgoDArIFfTDV2Z7BmK9O7/csqWSA0Y3xo8s26fvHqkH/zOu4shJ82pSacc2xKZ1z3PGDfVghtmI1+7nkAsq71hvJS2pwsIy6IA9JsUXXTrZ2Tjo2Twk=
env:
  global:
    secure: o1VZ74oj+vPJ/AYT7jYmiXDAFqRz58JsUrU2BDmLhat237uhohp/bpIBbxZupHjTDEmapRFPngcOVV23OZrR9+lYpJmwn2Nv1ezivKhBbSFFPUoAUJAzDhQD/+aVbp43YKsHzjhG5bg0tpiPrw/MGW3y9jVnhFmRGssLWUHO9z5PhErVLPjhdhqRs1/pripA+wiLqtGD43jJrn2MMSNTqqBKilwYvV0wI7Xo4FgCMJjpqvRxEj7PwAssyUiQqzWmceNiiKpS6HSXR9S7iG2Zjz/uMFIeVnCca69qLca/7dbjFOAtVJF9o2FspDsg5ipZ2wkJWomtf49vku/fWHL7b+mepgs8buxPqu14Yyawz6BLso2YFC5Zm6RZmLWYGl9xr3dRmQbd4o3kQhkSIQJonbm8GI2rrj8V6TNCBWNJdnqXvURTquJVtqqsyxR5zghGQDxO7p5SK79KIFIsHtYt2VTF/CaxaTR9xHs+/W6KSYNEXO/zYME9wy51gX5p0iY+V8BCMm6eaWcC8uiPppCRb4PoLzp7vaJDGawKLvWWfEaW1xhC0CmMCyk2dgoDArIFfTDV2Z7BmK9O7/csqWSA0Y3xo8s26fvHqkH/zOu4shJ82pSacc2xKZ1z3PGDfVghtmI1+7nkAsq71hvJS2pwsIy6IA9JsUXXTrZ2Tjo2Twk=
after_deploy:
- npm run benchmark
